- shell:
  - [mkdir -p ~/.config/i3]
  - [/bin/ls -Q | grep -v *work | xargs cat > i3/config/config]

- link:
    ~/.config/i3/config: i3/config/config
    ~/.config/i3/i3blocks.conf: i3/i3blocks.conf
    ~/.config/i3/lock: i3/i3lock-multimonitor/lock
    ~/.config/i3/img: i3/i3lock-multimonitor/img

