- shell:
  - [mkdir -p ~/.config/urxvt]

- link:
    ~/.Xresources: urxvt/Xresources
    ~/.config/urxvt/font-size: urxvt/urxvt-font-size/font-size
    ~/.config/urxvt/keyboard-select: urxvt/urxvt-perls/keyboard-select
    ~/.config/urxvt/url-select: urxvt/urxvt-perls/deprecated/url-select
    ~/.config/urxvt/nord: urxvt/nord-xresources/src/nord

