- shell:
  - [mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/temp_dirs/undodir]

- link:
    ~/.vimrc: vim/vimrc
    ~/.vim/plugins.vim: vim/plugins.vim
    ~/.vim/bundle/gundo: vim/bundle/gundo.vim
    ~/.vim/bundle/nerdtree: vim/bundle/nerdtree
    ~/.vim/bundle/nerdcommenter: vim/bundle/nerdcommenter
    ~/.vim/bundle/tagbar: vim/bundle/tagbar


