- shell:
  - [mkdir -p ~/.config/zsh/functions ~/.config/zsh/aliases]
  - [rm -rf ~/.zshrc]

- link:
    ~/.zshenv: zsh/zshenv
    ~/.config/zsh/.zshrc: zsh/zshrc
    ~/.config/zsh/.zlogin: zsh/zlogin
    ~/.config/zsh/completions.zsh: zsh/completions.zsh
    ~/.config/zsh/dir_colors.zsh: zsh/dir_colors.zsh
    ~/.config/zsh/keybindings.zsh: zsh/keybindings.zsh
    ~/.config/zsh/options.zsh: zsh/options.zsh
    ~/.config/zsh/prompt.zsh: zsh/prompt.zsh
    ~/.config/zsh/aliases/aliases.zsh: zsh/aliases/aliases.zsh
    ~/.config/zsh/aliases/common.zsh: zsh/aliases/common.zsh
    ~/.config/zsh/functions/functions.zsh: zsh/functions/functions.zsh
    ~/.config/zsh/functions/history-search-end: zsh/functions/history-search-end
    ~/.config/zsh/functions/history-search-multi-word: zsh/functions/history-search-multi-word/history-search-multi-word
    ~/.config/zsh/functions/prompt_spaceship_setup: zsh/functions/spaceship-prompt/spaceship.zsh
    ~/.config/zsh/functions/vi-mode.zsh: zsh/functions/vi-mode.zsh
    ~/.config/zsh/functions/zsh-autosuggestions.zsh: zsh/functions/zsh-autosuggestions/zsh-autosuggestions.zsh
    ~/.config/zsh/functions/zsh-syntax-highlighting.zsh: zsh/functions/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


