---
- name: EndeavourOS Dotfiles Setup
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    dotfiles_dir: "{{ playbook_dir | dirname }}"
    
    pacman_packages:
      - docker
      - maim
      - xclip
      - xdotool
      - playerctl
      - xss-lock
      - thunar
      - xfce4-terminal
      - unrar
      - p7zip
      - unzip
      - tree
      - pv
      - ttf-jetbrains-mono-nerd
      - gsimplecal
    
    aur_packages:
      - mise-bin
      - dotter-rs-bin
      - betterlockscreen
    
  tasks:
    - name: Install pacman packages
      become: yes
      pacman:
        name: "{{ pacman_packages }}"
        state: present
        update_cache: yes
    
    - name: Install AUR packages
      shell: yay -S --needed --noconfirm {{ aur_packages | join(' ') }}
      register: aur_result
      changed_when: "'installing' in aur_result.stdout"
    
    - name: Configure mise
      block:
        - name: Check if mise is available
          command: which mise
          register: mise_check
          failed_when: false
          changed_when: false
        
        - name: Trust mise global config
          shell: mise trust ~/.config/mise/config.toml
          when: mise_check.rc == 0
        
        - name: Install all mise tools
          shell: mise install -y
          args:
            chdir: "{{ dotfiles_dir }}"
          register: mise_install
          changed_when: mise_install.rc == 0
          when: mise_check.rc == 0
    
    - name: Deploy dotfiles
      shell: dotter deploy --force
      args:
        chdir: "{{ dotfiles_dir }}"
      register: dotter_deploy
      changed_when: dotter_deploy.rc == 0
    
    - name: Docker configuration
      become: yes
      block:
        - name: Add user to docker group
          user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: yes
        
        - name: Enable docker service
          systemd:
            name: docker
            enabled: yes
            state: started
    
    - name: Setup complete
      debug:
        msg:
          - "✅ Done! Please logout and login again."
          - "Run: exec zsh"