---
- name: Dotfiles Setup
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    dotfiles_dir: "{{ playbook_dir | dirname }}"
    profile: "{{ profile | default('full') }}"

    # Generic package names (distro-agnostic where possible)
    common_packages:
      - git
      - curl
      - unzip
      - tree

    # Arch-specific packages
    arch_packages:
      - docker
      - maim
      - xclip
      - xdotool
      - playerctl
      - xss-lock
      - thunar
      - xfce4-terminal
      - unrar
      - p7zip
      - pv
      - ttf-jetbrains-mono-nerd
      - gsimplecal

    # Debian/Ubuntu packages
    debian_packages:
      - docker.io
      - maim
      - xclip
      - xdotool
      - playerctl
      - xss-lock
      - thunar
      - xfce4-terminal
      - unrar
      - p7zip-full
      - pv
      - fonts-jetbrains-mono

    # AUR packages (Arch only)
    aur_packages:
      - mise-bin
      - dotter-rs-bin
      - betterlockscreen

  tasks:
    - name: Install common packages
      become: yes
      package:
        name: "{{ common_packages }}"
        state: present

    - name: Install Arch packages
      become: yes
      pacman:
        name: "{{ arch_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    - name: Install Debian/Ubuntu packages
      become: yes
      apt:
        name: "{{ debian_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install AUR packages (Arch only)
      shell: yay -S --needed --noconfirm {{ aur_packages | join(' ') }}
      register: aur_result
      changed_when: "'installing' in aur_result.stdout"
      when: ansible_os_family == "Archlinux"

    - name: Install mise (non-Arch)
      shell: curl https://mise.run | sh
      args:
        creates: ~/.local/bin/mise
      when: ansible_os_family != "Archlinux"

    - name: Install dotter (non-Arch)
      shell: |
        curl -fsSL https://github.com/SuperCuber/dotter/releases/latest/download/dotter-x86_64-unknown-linux-gnu -o ~/.local/bin/dotter
        chmod +x ~/.local/bin/dotter
      args:
        creates: ~/.local/bin/dotter
      when: ansible_os_family != "Archlinux"
    
    - name: Configure mise
      block:
        - name: Check if mise is available
          command: which mise
          register: mise_check
          failed_when: false
          changed_when: false
        
        - name: Trust mise global config
          shell: mise trust ~/.config/mise/config.toml
          when: mise_check.rc == 0
        
        - name: Install all mise tools
          shell: mise install -y
          args:
            chdir: "{{ dotfiles_dir }}"
          register: mise_install
          changed_when: mise_install.rc == 0
          when: mise_check.rc == 0
    
    - name: Select dotter profile
      copy:
        src: "{{ dotfiles_dir }}/.dotter/profiles/{{ profile }}.toml"
        dest: "{{ dotfiles_dir }}/.dotter/local.toml"
        force: yes

    - name: Deploy dotfiles
      shell: dotter deploy --force
      args:
        chdir: "{{ dotfiles_dir }}"
      register: dotter_deploy
      changed_when: dotter_deploy.rc == 0
    
    - name: Docker configuration
      become: yes
      ignore_errors: yes
      block:
        - name: Add user to docker group
          user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: yes

        - name: Enable docker service
          systemd:
            name: docker
            enabled: yes
            state: started
    
    - name: Setup complete
      debug:
        msg:
          - "✅ Done! Profile: {{ profile }}"
          - "Please logout and login again, or run: exec zsh"