version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup:
    desc: Complete setup (tools + configs)
    cmds:
      - task: tools
      - task: deploy
      - echo "Setup complete! Run exec zsh"

  deploy:
    desc: Deploy configurations
    cmds:
      - dotter deploy

  tools:
    desc: Install development tools
    cmds:
      - mise install
    sources:
      - mise.toml

  status:
    desc: Show status
    cmds:
      - git status -sb
      - dotter --version
      - mise list --current

  update:
    desc: Update and deploy
    cmds:
      - git pull
      - task: deploy

  backup:
    desc: Create backup
    cmds:
      - |
        backup_dir="$HOME/.local/share/dotfiles-backups/$(date +%Y%m%d-%H%M%S)"
        mkdir -p "$backup_dir"
        rsync -av --exclude='.git' --exclude='.idea' . "$backup_dir/"
        echo "Backup created: $backup_dir"

  # Extended tasks
  deploy:force:
    desc: Force deploy (overwrite conflicts)
    cmds:
      - dotter deploy --force

  undeploy:
    desc: Remove deployed symlinks
    cmds:
      - dotter undeploy

  upgrade:
    desc: Upgrade all tools
    cmds:
      - mise upgrade

  watch:
    desc: Watch and auto-deploy
    cmds:
      - dotter watch