version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dotfiles using yadm
    cmds:
      - echo "Installing dotfiles with yadm..."
      - yadm alt
      - yadm bootstrap
      - echo "✅ Dotfiles installed successfully!"

  update:
    desc: Update dotfiles from repository
    cmds:
      - echo "Updating dotfiles..."
      - yadm pull
      - yadm alt
      - echo "✅ Dotfiles updated!"

  status:
    desc: Show yadm repository status
    cmds:
      - yadm status

  templates:
    desc: Process yadm templates
    cmds:
      - echo "Processing yadm templates..."
      - yadm alt
      - echo "✅ Templates processed!"

  bootstrap:
    desc: Run yadm bootstrap scripts
    cmds:
      - echo "Running bootstrap scripts..."
      - yadm bootstrap
      - echo "✅ Bootstrap complete!"

  encrypt:
    desc: Encrypt sensitive files
    cmds:
      - yadm encrypt

  decrypt:
    desc: Decrypt sensitive files
    cmds:
      - yadm decrypt

  config:
    desc: Show yadm configuration
    cmds:
      - yadm config --list

  test-shell:
    desc: Test zsh configuration syntax
    cmds:
      - echo "Testing zsh configuration..."
      - zsh -n ~/.config/zsh/zshrc
      - echo "✅ Zsh config syntax OK!"