# Environment configuration
export DOTDIR="$HOME/git/dotfiles"
export CONFIG_DIR=${XDG_CONFIG_HOME:="${HOME}/.config"}
export CACHE_DIR=${XDG_CACHE_HOME:="${HOME}/.cache"}
export ZDOTDIR="$CONFIG_DIR/zsh"
export ZSH_CACHE_DIR="$CACHE_DIR/zsh"
export HISTFILE="$CACHE_DIR/.zhistory"
export EDITOR="vim"
export VISUAL="$EDITOR"
export BROWSER="firefox"
export PAGER="less"
export EXA_COLORS="sn=32;4:sb=32;4:da=1"
export PYENV_ROOT="$CONFIG_DIR/pyenv"
export POETRY_PATH="$HOME/.local"
export PYTHON_CONFIGURE_OPTS="--enable-optimizations"
export CFLAGS="-O3 -march=native"
export GOPATH="$CONFIG_DIR/go"
export NVM_DIR="$CONFIG_DIR/nvm"
export IPYTHONDIR="$CONFIG_DIR/ipython"
export JUPYTER_CONFIG_DIR="$CONFIG_DIR/jupyter"

eval "$(dircolors -b)"

typeset -U path
path=($PYENV_ROOT/bin $POETRY_PATH/bin ~/.cargo/bin $GOPATH/bin /usr/local/bin $path)
