#!/bin/sh

# https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

export TERMINAL=alacritty
export MON_1=HDMI-1
export MON_2=eDP-1

userresources=$HOME/.Xresources
[ -f $userresources ] && xrdb -merge "$userresources" &
setxkbmap -layout br &
xset b off &
$XDG_CONFIG_HOME/.screenlayout.sh &
$XDG_CONFIG_HOME/.fehbg
