[build]
jobs = 4
target-dir = "/tmp/rust-target"

[install]
root = "$HOME/.local"

[net]
git-fetch-with-cli = true

[registry]
default = "crates-io"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]