set nocompatible              
filetype off                  

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'wincent/command-t'
" Plugin 'davidhalter/jedi-vim'
Plugin 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }
Plugin 'airblade/vim-gitgutter'
Plugin 'mhinz/vim-startify'

call vundle#end()            

filetype plugin on   
filetype indent on   

syntax on 

set autoread

" ruler and line numbers
set ruler
set number

" search
set ignorecase
set smartcase

" tabs
set expandtab
set smarttab

set showmatch
set history=1500
set updatetime=100
