# Bun configuration - XDG Base Directory compliant
# https://bun.sh/docs/runtime/bunfig

[install]
# Where global packages are installed (XDG_DATA_HOME)
globalDir = "~/.local/share/bun/install/global"

# Global bin directory (XDG_BIN_HOME standard location)
globalBinDir = "~/.local/bin"

# Auto-install peer dependencies
peer = false

# Install optional dependencies
optional = false

# Install development dependencies for global packages
dev = false

[install.cache]
# Cache directory (XDG_CACHE_HOME)
dir = "~/.cache/bun"

# Disable cache
disable = false

# Don't save lockfile
disableManifest = false

[install.lockfile]
# Save lockfile
save = true

# Print a yarn-like lockfile
print = "bun"

[test]
# Default timeout for tests
timeout = 60000

[run]
# Silent mode
silent = false