# Global mise configuration
# https://mise.jdx.dev/
# This gets deployed to ~/.config/mise/config.toml via dotter

[tools]
# Languages
node = "lts"
python = "3.12"
go = "latest"
rust = "stable"  # Use stable for rust, not latest
bun = "latest"

# Editors
neovim = "latest"       # Neovim via mise

# Modern CLI tools (replacements for standard Unix tools)
bat = "latest"        # Better cat with syntax highlighting
eza = "latest"        # Better ls with colors and icons
fd = "latest"         # Better find with simpler syntax
ripgrep = "latest"    # Better grep (rg command)
fzf = "latest"        # Fuzzy finder for shell
starship = "latest"   # Modern shell prompt
delta = "latest"      # Better git diff viewer
dust = "latest"       # Better du with visualization
btop = "latest"       # Better top/htop
yq = "latest"         # YAML processor
jq = "latest"         # JSON processor
sd = "latest"         # Better sed for find/replace
hyperfine = "latest"  # Command benchmarking
tokei = "latest"      # Code statistics

# Shell enhancements
zoxide = "latest"     # Better cd with learning
atuin = "latest"      # Shell history database

# Git tools
lazygit = "latest"    # Terminal UI for git
gh = "latest"         # GitHub CLI
glab = "latest"       # GitLab CLI

# Development tools
direnv = "latest"     # Directory-specific environments
watchexec = "latest"  # File watcher for commands
just = "latest"       # Command runner (like make)
glow = "latest"       # Markdown renderer in terminal
bottom = "latest"     # Alternative system monitor

# Container tools
lazydocker = "latest" # Terminal UI for docker
docker-compose = "latest"
kubectl = "latest"
k9s = "latest"
helm = "latest"

# Security tools
age = "latest"        # Modern encryption
sops = "latest"       # Secrets management

# NPM global packages (via mise)
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@marp-team/marp-cli" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:npm-check" = "latest"
"npm:serve" = "latest"
"npm:repomix" = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:mcp-chrome-bridge" = "latest"
"npm:task-master-ai" = "latest"
"npm:ccstatusline" = "latest"

# Python tools (via pipx backend)
"pipx:claude-monitor" = "latest"
"pipx:crawl4ai" = "latest"
"pipx:gitingest" = "latest"
"pipx:llm" = "latest"

[env]
# Global environment variables set by mise
EDITOR = "nvim"
VISUAL = "nvim"
PAGER = "less"
LANG = "en_US.UTF-8"
GOPATH = "/opt/go"
