#!/bin/sh

# https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

export EDITOR=vim
export TERMINAL=alacritty
export MON_1=HDMI-0
export MON_2=DP-2

xset b off
