# a-$
alias a='alias'
alias b='bat'
alias c='oco'
alias d='dust'
alias f='fd'
alias g='gpt'
alias h='histdb'
alias j='z'
alias l='ls'
alias m='man'
alias p='pip'
alias q='exit'
alias s='sudo'
alias t='tree'
alias v='vim'
alias y='yay'
alias \$=''

# cd
alias .='cd ./'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias .......='cd ../../../../../../'
alias ........='cd ../../../../../../../'
alias .........='cd ../../../../../../../../'
alias ..........='cd ../../../../../../../../../'

# clipboard
alias copy='xsel -ib'
alias paste='xsel -o'
alias xcopy='xclip -sel clip'

# docker
alias dc='docker-compose'
alias dcu='docker-compose up -d'
alias dcuf='docker-compose up -d --force-recreate'
alias dcd='docker-compose down'
alias dcs='docker-compose stop'
alias dcc="docker-compose config"
alias dcp='docker-compose pull'
alias dcl='docker-compose logs --tail=100 -f'
alias deit='docker exec -it'
alias dci='docker inspect'
alias dim='docker images'
alias dip='docker image prune -f'
alias dl='docker logs'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dr='docker restart'
alias drit='docker run -it'
alias drm='docker rm'
alias ds='docker start'
alias dsp='docker system prune --all'
alias lzd='lazydocker'

# ext
alias bat='bat --paging=never'
alias cht='cht.sh'
alias du='dust'
alias du1='dust -d 1'
alias dud='dust -d'
alias fox='firefox'
alias gpt='sgpt'
alias gpt3='sgpt --model gpt-3.5-turbo-0125'
alias gpt4='sgpt --model gpt-4o'
alias gsh='sgpt --shell'
alias gpc='sgpt --code'
alias pom='potato'
alias psg='psgrep'

# fd
alias noeclipse="fd '\.(settings|classpath|factorypath|project)' -tf -X rm"
alias noidea="find . -type d -name '.idea' -exec rm -rf {} +"
alias nomac="fd -H '^\.DS_Store$' -tf -X rm"
alias nopyc="fd -H 'pyc(ache)?' -X rm -r"

# git
alias ga='git add'
alias ga.='git add .'
alias gaa='git add --all'
alias gap='git add -p'
alias gua='git restore --staged'
alias gb='git branch'
alias gbl='git branch --list'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gcam='git commit --amend -m'
alias gcl='git clone'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcb='git checkout -B'
alias gd='git diff --color-words'
alias gd.='git diff .'
alias gdc='git diff --cached'
alias gss='git reset --soft'
alias gshr='git reset --hard && echo "Are you sure? [y/N]" && read -r ans && if [[ $ans != y ]]; then exit 1; fi'
alias gf='git fetch --all --prune'
alias gpl='git pull'
alias gplr='git pull --rebase'
alias gplm='git pull --no-rebase'
alias gp='git push -u origin $(git rev-parse --abbrev-ref HEAD)'
alias gpf='git push --force-with-lease'
alias gl='git log --stat'
alias glg='git log --oneline --decorate --all --graph'
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gls='git log --stat'
alias glod='git log --oneline --decorate --graph --date-order'
alias gm='git merge --no-ff'
alias gmo='git merge --strategy=ours'
alias gmt='git merge --strategy=theirs'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias gri='git rebase -i'
alias grbm='git rebase main'
alias gs='git status -sb'
alias gs.='git status .'
alias gsb='git submodule'
alias gsl='git submodule status'
alias gsu='git submodule update --init --recursive'
alias gsba='git submodule add'
alias gst='git stash push -m "WIP: $(date +%Y-%m-%d_%H-%M-%S)"'
alias gut='git stash pop'
alias gsta='git stash apply'
alias gsts='git stash save'
alias gstl='git stash list'
alias grm='git rm'
alias grmc='git rm --cached'
alias authors="git ls-files | while read f; do git blame -w -M -C -C --line-porcelain \$f | grep -I '^author '; done 2>/dev/null | sort -f | uniq -ic | sort -n"

# gradle
alias grd='./gradlew'
alias grdc='./gradlew clean'
alias grdb='./gradlew build'
alias grdr='./gradlew bootRun'
alias grdbr='./gradlew build --refresh-dependencies'
alias grdi='./gradlew install'
alias grdcb='grdc && grdb'
alias grdci='grdc && grdi'

# grep
alias grep='grep --color=auto --ignore-case'
alias fgrep='grep --fixed-strings'
alias egrep='grep --extended-regexp'
alias lgrep="grep -rnw '.' -e"
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS}'

# kill
alias ka='killall'
alias k9='kill -9'

# linux
alias all='alias'
alias cdd='cd ~/Downloads'
alias cdc='cd ~/Documents'
alias cdp='cd ~/Pictures'
alias chx='chmod +x'
alias cp='cp -R'
alias df='df -h'
alias m1='man 1'
alias md='mkdir'
alias mkdir='mkdir -p'
alias off='xset dpms force off'
alias rf='readlink -f'
alias rmrf='rm -rf'
alias tf='tail -F'
alias xrl='xrdb -load ~/.Xresources'
alias zshd='zsh -xv &>> (tee ~/zsh-debug.log 2>/dev/null)'

# ls
alias ls='exa --colour=always'
alias la='exa -la'
alias lr='exa -R'
alias lra='exa -Ra'
alias l.='exa -d .*'
alias lse='exa --empty'
alias lsnew='exa --sort=modified --reverse'
alias lsold='exa --sort=modified'
alias lsmall='exa --sort=size'
alias lsbig='exa --sort=size --reverse'

# List only directories and symbolic
# links that point to directories
alias lsd='ls -ld *(-/DN) R|lsd'

# List only file beginning with "."
alias lsa='ls -ld .*'

# maven
alias mvc='mvn clean'
alias mvi='mvn install'
alias mvci='mvc && mvi'

# mount
alias mount='sudo mount'
alias umount='sudo umount'

# Network
alias ip='ip -color=auto'
alias ipv4='ip -4 addr'
alias ipv6='ip -6 addr'
alias hosts='cat /etc/hosts'
alias resolv='cat /etc/resolv.conf'
alias dns='resolvectl status'
alias pingd='ping -c3 archlinux.org'
alias ipe='curl ifconfig.me'
alias tracert='traceroute'
alias traces='sudo traceroute -I'
alias wget='wget -c'
alias speedtest='speedtest-cli'
alias netstat='netstat -tulnp'
alias iptables='sudo iptables -L -v -n'
alias curl='curl -v'
alias wifidev='nmcli device wifi list'
alias wifion='nmcli radio wifi on'
alias wifioff='nmcli radio wifi off'
alias wificonnect='nmcli device wifi connect'
alias wifiinfo='nmcli device show'
alias stopfw='sudo systemctl stop ufw'
alias startfw='sudo systemctl start ufw'
alias restartfw='sudo systemctl restart ufw'
alias tcpdump='sudo tcpdump -i any -nn -s 0 -vvv'
alias capture_http='sudo tcpdump -i any -nn -s 0 -vvv -A port 80'
alias capture_https='sudo tcpdump -i any -nn -s 0 -vvv port 443'
alias vhost='sudo vim /etc/hosts'
alias startvpn='sudo wg-quick up wg0'
alias stopvpn='sudo wg-quick down wg0'

# path
alias path='echo $PATH | tr -s ":" "\n"'
alias ppath='print -l $PATH'
alias fpath='echo $FPATH | tr -s ":" "\n"'
#alias lpath='echo $LPATH | tr -s ":" "\n"'

# ps
alias pmem='ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head'
alias pcpu='ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head'

# python
alias py='python3'
alias venv='virtualenv venv && source ./venv/bin/activate'
alias pyi='pyenv install'
alias pi='pip install'
alias pu='pip uninstall'
alias pupg='pip install --upgrade pip'
alias pfr='pip freeze > requirements.txt'
alias pre='pip install -r requirements.txt'
alias pt='poetry'
alias pa='poetry add'
alias pad='poetry add --group dev'
alias pb='poetry build'
alias pl='poetry lock'
alias prm='poetry remove'
alias pupd='poetry update'
alias pti='poetry install'
alias pid='poetry install --with=dev'
alias ptr='poetry run'
alias pyc='pycharm'
alias pysrv='python3 -m http.server'
alias pycol='pygmentize -l pytb'
alias json='python3 -m json.tool'
alias jup='jupyter notebook'
alias note='jupyter notebook'
alias sc='scrapy'
alias scc='scrapy crawl'
alias scs='scrapy shell'
alias server='python3 -m http.server'
alias color='pygmentize -l pytb'

# sudo
alias chown='sudo chown'
alias fdisk='sudo fdisk'
alias journal='sudo journalctl --since=today -f'

# tar
alias targz='tar xzf'
alias targzc='tar -czvf'
alias tarc='tar -cvf'
alias tarbz2='tar xjf'
alias tarxz='tar xf'
alias tarls='tar tvf'

# tree
alias t1='tree -L 1'
alias t2='tree -L 2'
alias t3='tree -L 3'
alias t4='tree -L 4'
alias t5='tree -L 5'

# vim
alias vi='vim'
alias nano='vim'
alias emacs='vim'
alias sv='sudo vim'
alias vimplug='vim +PluginInstall +qall'
