" Minimal Vim Configuration (Fallback)
" ====================================
" This is a minimal config for when nvim is not available

" Essential Settings
" ------------------
set number                      " Show line numbers
set relativenumber              " Show relative line numbers
set expandtab                   " Use spaces instead of tabs
set tabstop=4                   " Tab width
set shiftwidth=4                " Indent width
set autoindent                  " Copy indent from current line

" Search Settings
" ---------------
set ignorecase                  " Case insensitive search
set smartcase                   " Case sensitive if uppercase present
set hlsearch                    " Highlight search results
set incsearch                   " Incremental search

" Basic Usability
" ---------------
set wrap                        " Enable line wrapping
set linebreak                   " Wrap at word boundaries
set showmatch                   " Show matching brackets
set wildmenu                    " Command line completion
set backspace=indent,eol,start  " Sensible backspace

" Key Mappings
" ------------
" Save with Ctrl+S
nnoremap <C-s> :w<CR>
inoremap <C-s> <Esc>:w<CR>a

" Return to last edit position when opening files
autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") && &ft !~# 'commit'
    \ |   execute "normal! g`\""
    \ | endif

" Minimal color scheme
silent! colorscheme desert