# Dotter Global Configuration
# Use profiles in .dotter/profiles/ to select which packages to deploy

[shell.files]
# Core shell infrastructure
"shell/core/zsh/.zshenv" = "~/.zshenv"
"shell/core/zsh" = "~/.config/zsh"
"shell/core/zsh/conf.d/secrets.zsh.local" = "~/.config/zsh/conf.d/secrets.zsh"
"shell/core/bash/.bashrc" = "~/.bashrc"
"shell/core/bash/.bash_profile" = "~/.bash_profile"
"shell/core/ssh" = "~/.ssh"
"shell/core/mise/config.toml" = "~/.config/mise/config.toml"

# Development tools
"shell/development/git/git/config.hbs" = "~/.config/git/config"
"shell/development/git/git/config-work.hbs" = "~/.config/git/config-work"
"shell/development/git" = "~/.config/git"
"shell/development/cargo" = "~/.cargo"
"shell/development/bun/config.toml" = "~/.bunfig.toml"
"shell/development/go" = "~/.config/go"
"shell/development/pip" = "~/.config/pip"
"shell/development/pyenv" = "~/.pyenv"
"shell/development/uv/uv.toml" = "~/.config/uv/uv.toml"
"shell/development/docker/config" = { target = "~/.docker/config.json", type = "symbolic" }
"shell/development/docker/daemon.json.hbs" = "~/.docker/daemon.json"
"shell/development/ansible/ansible.cfg" = "~/.config/ansible/ansible.cfg"

# User applications
"shell/applications/atuin" = "~/.config/atuin"
"shell/applications/ranger" = "~/.config/ranger"
"shell/applications/claude/config.json" = "~/.claude/settings.json"
"shell/applications/repomix/repomix.config.json5" = "~/.config/repomix/repomix.config.json5"
"shell/applications/nvim" = "~/.config/nvim"
"shell/applications/vim" = "~/.config/vim"
"desktop/applications/sublime-text-3" = "~/.config/sublime-text-3"

# Scripts
"shell/scripts" = "~/.local/bin"

[desktop.files]
# Core desktop environment
"desktop/core/i3/config" = "~/.config/i3/config"
"desktop/core/i3/i3blocks/i3blocks.conf" = "~/.config/i3/i3blocks.conf"
"desktop/core/i3/i3wsr" = "~/.config/i3wsr"
"desktop/core/picom" = "~/.config/picom"
"desktop/core/autostart" = "~/.config/autostart"
"desktop/core/gtk-3.0" = "~/.config/gtk-3.0"
"desktop/core/gtk-4.0" = "~/.config/gtk-4.0"
"desktop/core/x11/Xresources" = "~/.Xresources"
"desktop/core/x11/xprofile" = "~/.xprofile"
# System files should be deployed by Ansible, not dotter
# "desktop/core/lightdm/slick-greeter.conf" = { target = "/etc/lightdm/slick-greeter.conf", type = "symbolic" }

# Core desktop services
"desktop/core/dunst" = "~/.config/dunst"
"desktop/core/betterlockscreen/betterlockscreenrc" = "~/.config/betterlockscreenrc"

# Desktop applications
"shell/applications/rofi" = "~/.config/rofi"
"desktop/applications/xfce4" = "~/.config/xfce4"
"desktop/applications/gsimplecal" = "~/.config/gsimplecal"
"desktop/applications/firefox" = "~/.config/firefox"
"desktop/applications/obsidian/app.json" = "~/.config/obsidian/app.json"
"desktop/applications/obsidian/appearance.json" = "~/.config/obsidian/appearance.json"
"desktop/applications/obsidian/community-plugins.json" = "~/.config/obsidian/community-plugins.json"
"desktop/applications/jetbrains" = "~/.config/jetbrains"
"desktop/applications/kalu" = "~/.config/kalu"

# Desktop assets
"desktop/assets/wallpapers" = { target = "~/.config/wallpapers", type = "symbolic" }
# System files should be deployed by Ansible, not dotter
# "shell/core/pacman/pacman.conf" = { target = "/etc/pacman.conf", type = "symbolic" }
