if (( ! EUID )); then
    HISTFILE=$ZSH_CACHE/history_root
else
    HISTFILE=$ZSH_CACHE/history
fi

SAVEHIST=10000
HISTSIZE=12000

setopt SHARE_HISTORY 
setopt APPEND_HISTORY 
setopt EXTENDED_HISTORY 
setopt HIST_NO_STORE 
setopt HIST_IGNORE_ALL_DUPS 
setopt HIST_IGNORE_SPACE

setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt EXTENDED_GLOB
setopt NOMATCH
setopt NO_BEEP
setopt TRANSIENT_RPROMPT
setopt COMPLETE_IN_WORD
setopt NO_CLOBBER
