typeset -U path
path=($path[@] ~/.local/bin $HOME/.cargo/bin)

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZFUNCTIONS="$ZDOTDIR/functions"
export ZALIASES="$ZDOTDIR/aliases"
export ZSH_CACHE="$XDG_CACHE_HOME/zsh"
mkdir -p $ZSH_CACHE

export VISUAL="vim"
export EDITOR="$VISUAL"

export MOZ_PATH="$HOME/.mozilla/firefox/"
export BROWSER="firefox"

export ANTIGEN_PATH="/home/morel/dotfiles/zsh/antigen"

