# Environment configuration
export DOTDIR=$HOME/git/dotfiles                        # Dotfiles location
export ZDOTDIR=~/.config/zsh                            # zsh configs
export ZSH_CACHE_DIR=~/.cache/zsh                       # caching zsh data
export EDITOR=vim                                       # Vim.
export VISUAL=$EDITOR                                   # Default visual editor
export BROWSER=firefox                                  # Firefox web browser
export PAGER=less                                       # Default pager to less.
export EXA_COLORS="sn=32;4:sb=32;4:da=1"                # Turn the date column green
export PYENV_ROOT="$HOME/.config/pyenv"
export POETRY_PATH="$HOME/.local"
export PYTHON_CONFIGURE_OPTS='--enable-optimizations --with-lto' PYTHON_CFLAGS='-march=native -mtune=native'
#export GOROOT="/usr/local/go"
export GOPATH=$HOME/.config/go
export NVM_DIR="$HOME/.config/nvm"
export IPYTHONDIR="$HOME/.config/ipython"
export JUPYTER_CONFIG_DIR="$HOME/.config/jupyter"
eval "$(dircolors -b)"
#export CONDA_DIR="$HOME/.config/conda/miniconda3"
typeset -U path
path=($PYENV_ROOT/bin $POETRY_PATH/bin ~/.local/bin ~/.cargo/bin $GOPATH/bin /usr/local/bin $path /usr/local/go/bin)

