# https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE="$XDG_CACHE_HOME/zsh" 
export ZFUNCTIONS="$ZDOTDIR/functions"
export ZALIASES="$ZDOTDIR/aliases"
export ZCOMMON="$ZDOTDIR/common"

export VISUAL="vim"
export EDITOR="$VISUAL"
export BROWSER="firefox"

export MOZ_PATH="$HOME/.mozilla/firefox/"
export PIP_PATH="$HOME/.local/bin"
export RUST_PATH="$HOME/.cargo/bin"
export GOPATH="$HOME/.go"

typeset -U path
path=($path[@] $PIP_PATH $RUST_PATH $GOPATH/bin)

export LESS='-R --use-color -Dd+r$Du+b'
