fpath=( ~/Devel/dotfiles/zsh/functions/zsh-completions/src $ZFUNCTIONS $fpath )

typeset -ga sources
sources+="$ZDOTDIR/options.zsh"
sources+="$ZDOTDIR/aliases/aliases.zsh"
sources+="$ZDOTDIR/dir_colors.zsh"
sources+="$ZDOTDIR/completions.zsh"
sources+="$ZDOTDIR/keybindings.zsh"
sources+="$ZDOTDIR/prompt.zsh"
sources+="$ZFUNCTIONS/functions.zsh"

foreach file (`echo $sources`)
    if [[ -a $file ]]; then
        source $file
    fi
end
