#
# ZSH VERSION: zsh 5.8.1 (x86_64-pc-linux-gnu)
#
# .zshrc is sourced in interactive shells.  It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.
#


# Use hard limits, except for a smaller stack and no core dumps
unlimit
limit stack 8192
limit core 0
limit -s

umask 022


TRAPUSR1() { rehash }


rec_source() {
    local f
    for f in "$1"/*; do
        [[ -d $f ]] && rec_source "$f"
        [[ -L $f ]] && [[ $f == *.zsh ]] && source $f # && printf '%s\n' $f
    done
}


# Set/unset  shell options
source $ZCOMMON/options.zsh


# Set color prompt
source $ZCOMMON/prompt.zsh

# Setup completion system
autoload -U compinit; compinit -d $ZSH_CACHE/.zcompinit
source $ZCOMMON/completions.zsh


# Some nice key bindings
source $ZCOMMON/keybindings.zsh


# Where to look for autoloaded function definitions
# fpath=($fpath $ZFUNCTIONS)

# Autoload all shell functions from all directories in $fpath (following
# symlinks) that have the executable bit on (the executable bit is not
# necessary, but gives you an easy way to stop the autoloading of a
# particular shell function). $fpath should not be empty for this to work.
# for func in $^fpath/*(N-.x:t); autoload $func
rec_source $ZFUNCTIONS


# Resets the terminal with escape sequences
function reset_broken_terminal () {
    printf '%b' '\e[0m\e(B\e)0\017\e[?5l\e7\e[0;0r\e8'
}

add-zsh-hook -Uz precmd reset_broken_terminal


colorscript -r


# Set up aliases
rec_source $ZALIASES

