[icons]
firefox = ""
chromium = ""
google-chrome = ""
Google-chrome = ""
kitty = ""
alacritty = ""
xfce4-terminal = ""
Xfce4-terminal = ""
gnome-terminal = ""
code = ""
vim = ""
nvim = ""
jetbrains-pycharm-ce = ""
thunar = ""
Thunar = ""
discord = ""
spotify = ""
vlc = ""
gimp = ""
obsidian = ""
docker = ""
remmina = ""
"org.remmina.Remmina" = ""
code-oss = ""
"code-oss" = ""
libreoffice = ""
"libreoffice-startcenter" = ""
"libreoffice-writer" = ""
"libreoffice-calc" = ""
"libreoffice-impress" = ""
"libreoffice-draw" = ""
"libreoffice-base" = ""
"libreoffice-math" = ""

[general]
default_icon = ""

[options]
remove_duplicates = true
no_names = true
