# Full profile: everything (shell + dev + GUI + system)
# For desktop workstations

packages = ["shell", "dev", "gui", "system"]

[variables]
hostname = "stable"
distro = "Arch"
is_desktop = true
is_laptop = false
monitors = "dual"
