# Full profile: everything (shell + desktop)
# For desktop workstations

packages = ["shell", "desktop"]

[variables]
hostname = "stable"
distro = "Arch"
is_desktop = true
is_laptop = false
monitors = "dual"
