# Minimal profile: shell tools only (no GUI)
# For servers, code-server, containers, remote machines

packages = ["shell"]

[variables]
hostname = "stable"
distro = "Debian"
is_desktop = false
is_laptop = false
