# Minimal profile: shell + dev tools only (no GUI)
# For servers, code-server, containers, remote machines

packages = ["shell", "dev"]

[variables]
hostname = "stable"
distro = "Arch"
is_desktop = false
is_laptop = false
